version: '3'

services:
  mysql:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users_db
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'
    volumes:
    - mysql_data:/designs
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data: